// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDaKsEXCjnVZigabgHoIaUKSQQTKhu6r8s',
//     appId: '1:475352204751:web:9527165bf6dcaa6632feba',
//     messagingSenderId: '475352204751',
//     projectId: 'locomo-ae5f7',
//     authDomain: 'locomo-ae5f7.firebaseapp.com',
//     storageBucket: 'locomo-ae5f7.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDru2TwDyui3HH6PcC0PFSxRrv3CJY2b_8',
//     appId: '1:475352204751:android:45e08f64449de82932feba',
//     messagingSenderId: '475352204751',
//     projectId: 'locomo-ae5f7',
//     storageBucket: 'locomo-ae5f7.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBt1LMOXrL-QTO8rjMIEFWKgQQRcEWmJxs',
//     appId: '1:475352204751:ios:8983669f430dde2c32feba',
//     messagingSenderId: '475352204751',
//     projectId: 'locomo-ae5f7',
//     storageBucket: 'locomo-ae5f7.firebasestorage.app',
//     iosBundleId: 'com.example.locomoApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBt1LMOXrL-QTO8rjMIEFWKgQQRcEWmJxs',
//     appId: '1:475352204751:ios:8983669f430dde2c32feba',
//     messagingSenderId: '475352204751',
//     projectId: 'locomo-ae5f7',
//     storageBucket: 'locomo-ae5f7.firebasestorage.app',
//     iosBundleId: 'com.example.locomoApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDaKsEXCjnVZigabgHoIaUKSQQTKhu6r8s',
//     appId: '1:475352204751:web:c8b0e7551041e17932feba',
//     messagingSenderId: '475352204751',
//     projectId: 'locomo-ae5f7',
//     authDomain: 'locomo-ae5f7.firebaseapp.com',
//     storageBucket: 'locomo-ae5f7.firebasestorage.app',
//   );
// }
